blank_issues_enabled: false
contact_links:
  - name: Feature Requests
    url: https://github.com/longshotlabs/js-message-box/discussions
    about: Request new features and product improvements on GitHub Discussions.
